Adding participant removal by Button & confirm modal and by timeout.
scaled-agile-inc/planning-poker pull request #2
Opened 2022-09-30 14:10 UTC by tuhlmann

This PR adds two features around participant removal:

1) There's a top centered button to kick our ALL participants from a room:

<img width="1492" alt="2022-09-30_16-05-47" src="https://user-images.githubusercontent.com/407319/193287817-d522a643-074f-4281-a350-d0c7eb8f920c.png">

<img width="586" alt="2022-09-30_16-05-56" src="https://user-images.githubusercontent.com/407319/193287833-d25cc583-80fc-43fe-b0ab-a982063d28bb.png">

<img width="1927" alt="2022-09-30_16-06-08" src="https://user-images.githubusercontent.com/407319/193287871-cf8ba670-5a5a-421f-8a13-14f7df4f365b.png">

This opens a modal and when confirmed will remove all, active and inactive, users from this room and, if these are the only rooms they are in, will remove them from the players list as well.

**Caveat:**

The user that kicked off the removed all see the name modal again to enter a new name. Any other users still logged in will need to refresh their page to see the name modal. Please advice on how this could best be solved.

1) Everytime a player is updated, a lastSeen timestamp is renewed. If that timestamp is older than 24h, the user is removed from all rooms he's in and then from the players list as well.

**Caveat:**

There is currenly no board update if a use has been automatically been removed. Please advice on how to best add this.

2022-09-30 16:30 UTC, tuhlmann commented
@mikepray Both issues are now fixed- any still open browser window will trigger the re-join by showing the name modal and then adds that new user to the board, no browser refresh necessary.

2022-10-07 21:26 UTC, mikepray requested changes
Looking great, did some testing and kicking participants works great. Some minor feedback in the changes requested.

How should the cleanup timeout work? Is it supposed to kick idle participants, or participants that have closed their socket connection after an hour or a day?

2022-10-10 15:41 UTC, tuhlmann commented on pointer-backend/src/services/room.service.ts
> +export const deleteParticipants = (roomId: string): [boolean, Player[] | undefined] => {
Changed.

2022-10-10 15:43 UTC, tuhlmann commented on pointer-backend/src/services/room.service.ts
> +const playExistsInAnyRoom = (playerUid: string): boolean => {
Fixed.

2022-10-10 15:45 UTC, tuhlmann commented
@mikepray In player.service.ts I defined 2 timeouts:

```Typescript
```

2022-10-10 15:56 UTC, tuhlmann commented
I implemented the requested changes, ready for another look.

2022-10-11 20:40 UTC, mikepray approved these changes

2022-10-11 20:40 UTC, merged